@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzIwOTY3NDd9.RcGPdE5RggsVCECS-orU1PNWAVcOizF9tLJQDypvREE

@hostname = http://localhost:3000

### PRODUCTS INDEX
GET {{hostname}}/products?category=Playtime
Authorization: Bearer {{jwt}}
### PRODUCTS SHOW
GET {{hostname}}/products/2
### PRODUCTS CREATE
POST {{hostname}}/products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "",
  "price": 10000,
  "description": "water",
  "inventory": 1,
  "supplier_id": 2
}

### PRODUCTS UPDATE
PATCH {{hostname}}/products/2
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "inventory": 3 
}
### PRODUCTS DESTROY
DELETE {{hostname}}/products/5

### SUPPLIERS INDEX
GET {{hostname}}/suppliers
Authorization: Bearer {{jwt}}
### SUPPLIERS SHOW
GET {{hostname}}/suppliers/1
### SUPPLIERS CREATE
POST {{hostname}}/suppliers
Content-Type: application/json

{
  "name": "",
  "email": "",
  "phone_number": ""
}
### SUPPLIERS UPDATE
PATCH {{hostname}}/suppliers/1
Content-Type: application/json

{
  "phone_number": ""
}
### SUPPLIERS DESTROY
DELETE {{hostname}}/suppliers/2

### IMAGES CREATE
POST {{hostname}}/images
Content-Type: application/json

{
  "url": "https://9ed48207422fa7fc5013-a6297eb5ec0f30e883355c8680f3b2d6.ssl.cf2.rackcdn.com/RSG11%20(2)-20180815220434-20180815220922-1600x1075.jpg",
  "product_id": 4
}
### IMAGES UPDATE
PATCH {{hostname}}/images/4
Content-Type: application/json

{
  "product_id": 3
}
### IMAGES DESTROY
DELETE {{hostname}}/images/10



### Users create (signup)
  POST {{hostname}}/users
  Content-Type: application/json

  {
    "name": "Polly",
    "email": "polly@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }

### Sessions create (login)
  POST {{hostname}}/sessions
  Content-Type: application/json

  {
    "email": "minnie@gmail.com",
    "password": "password"
  }

### Carted Products Index
GET {{hostname}}/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Carted Products create
POST {{hostname}}/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
 
  "product_id": 4,
  "quantity": 3
 
}

### Carted Products Update/Destroy
PATCH {{hostname}}/carted_products/2
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Orders create
POST {{hostname}}/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Orders show
GET {{hostname}}/orders/3
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Orders index
GET {{hostname}}/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}
